# Datatype:
Datatype.create!([
  {id: 1, name: "System Uptime", oid: "SNMPv2-MIB::sysUpTime.0", excludes: "", table: false, index_oid: "", metric_type: "snmp_uptime", derive: false, default: true},
  {id: 2, name: "Interface Link Speed", oid: "IF-MIB::ifHighSpeed", excludes: "^(802|VI|Vl|Vi|Se|Lo|Nu|Tu|Vo|Vt|Aux|Console|NULL|System|MTun|InLoop|BV1|mcast|test|pim|TEST)", table: true, index_oid: "IF-MIB::ifName", metric_type: "snmp_if_linkspeed", derive: false, default: true},
  {id: 3, name: "Interface RX Bytes", oid: "IF-MIB::ifHCInOctets", excludes: "^(802|VI|Vl|Vi|Se|Lo|Nu|Tu|Vo|Vt|Aux|Console|NULL|System|MTun|InLoop|BV1|mcast|test|pim|TEST)", table: true, index_oid: "IF-MIB::ifName", metric_type: "snmp_if_traffic_rx", derive: true, default: true},
  {id: 4, name: "Interface TX Bytes", oid: "IF-MIB::ifHCOutOctets", excludes: "^(802|VI|Vl|Vi|Se|Lo|Nu|Tu|Vo|Vt|Aux|Console|NULL|System|MTun|InLoop|BV1|mcast|test|pim|TEST)", table: true, index_oid: "IF-MIB::ifName", metric_type: "snmp_if_traffic_tx", derive: true, default: true},
  {id: 5, name: "Interface RX Bytes (lowres)", oid: "IF-MIB::ifInOctets", excludes: "^(802|VI|Vl|Vi|Se|Lo|Nu|Tu|Vo|Vt|Aux|Console|NULL|System|MTun|InLoop|BV1|mcast|test|pim|TEST)", table: true, index_oid: "IF-MIB::ifName", metric_type: "snmp_if_traffic_rx", derive: true, default: false},
  {id: 6, name: "Interface TX Bytes (lowres)", oid: "IF-MIB::ifOutOctets", excludes: "^(802|VI|Vl|Vi|Se|Lo|Nu|Tu|Vo|Vt|Aux|Console|NULL|System|MTun|InLoop|BV1|mcast|test|pim|TEST)", table: true, index_oid: "IF-MIB::ifName", metric_type: "snmp_if_traffic_tx", derive: true, default: false},
  {id: 7, name: "Interface RX Unicast Frames", oid: "IF-MIB::ifHCInUcastPkts", excludes: "^(802|VI|Vl|Vi|Se|Lo|Nu|Tu|Vo|Vt|Aux|Console|NULL|System|MTun|InLoop|BV1|mcast|test|pim|TEST)", table: true, index_oid: "IF-MIB::ifName", metric_type: "snmp_if_ucast_rx", derive: true, default: false},
  {id: 8, name: "Interface TX Unicast Frames", oid: "IF-MIB::ifHCOutUcastPkts", excludes: "^(802|VI|Vl|Vi|Se|Lo|Nu|Tu|Vo|Vt|Aux|Console|NULL|System|MTun|InLoop|BV1|mcast|test|pim|TEST)", table: true, index_oid: "IF-MIB::ifName", metric_type: "snmp_if_ucast_tx", derive: true, default: false},
  {id: 9, name: "Interface RX Multicast Frames", oid: "IF-MIB::ifHCInMulticastPkts", excludes: "^(802|VI|Vl|Vi|Se|Lo|Nu|Tu|Vo|Vt|Aux|Console|NULL|System|MTun|InLoop|BV1|mcast|test|pim|TEST)", table: true, index_oid: "IF-MIB::ifName", metric_type: "snmp_if_mcast_rx", derive: true, default: false},
  {id: 10, name: "Interface TX Multicast Frames", oid: "IF-MIB::ifHCOutMulticastPkts", excludes: "^(802|VI|Vl|Vi|Se|Lo|Nu|Tu|Vo|Vt|Aux|Console|NULL|System|MTun|InLoop|BV1|mcast|test|pim|TEST)", table: true, index_oid: "IF-MIB::ifName", metric_type: "snmp_if_mcast_tx", derive: true, default: false},
  {id: 11, name: "Interface RX Broadcast Frames", oid: "IF-MIB::ifHCInBroadcastPkts", excludes: "^(802|VI|Vl|Vi|Se|Lo|Nu|Tu|Vo|Vt|Aux|Console|NULL|System|MTun|InLoop|BV1|mcast|test|pim|TEST)", table: true, index_oid: "IF-MIB::ifName", metric_type: "snmp_if_bcast_rx", derive: true, default: false},
  {id: 12, name: "Interface TX Broadcast Frames", oid: "IF-MIB::ifHCOutBroadcastPkts", excludes: "^(802|VI|Vl|Vi|Se|Lo|Nu|Tu|Vo|Vt|Aux|Console|NULL|System|MTun|InLoop|BV1|mcast|test|pim|TEST)", table: true, index_oid: "IF-MIB::ifName", metric_type: "snmp_if_bcast_tx", derive: true, default: false},
  {id: 13, name: "Interface RX Errors", oid: "IF-MIB::ifInErrors", excludes: "^(802|VI|Vl|Vi|Se|Lo|Nu|Tu|Vo|Vt|Aux|Console|NULL|System|MTun|InLoop|BV1|mcast|test|pim|TEST)", table: true, index_oid: "IF-MIB::ifName", metric_type: "snmp_if_err_rx", derive: true, default: true},
  {id: 14, name: "Interface TX Errors", oid: "IF-MIB::ifOutErrors", excludes: "^(802|VI|Vl|Vi|Se|Lo|Nu|Tu|Vo|Vt|Aux|Console|NULL|System|MTun|InLoop|BV1|mcast|test|pim|TEST)", table: true, index_oid: "IF-MIB::ifName", metric_type: "snmp_if_err_tx", derive: true, default: true},
  {id: 15, name: "Cisco: PPPoE Sessions", oid: "SNMPv2-SMI::enterprises.9.9.194.1.1.1.0", excludes: "", table: false, index_oid: "", metric_type: "snmp_pppoe_sess", derive: false, default: false},
  {id: 16, name: "Cisco: PPPoE Highwater Sessions", oid: "SNMPv2-SMI::enterprises.9.9.194.1.1.2.0", excludes: "", table: false, index_oid: "", metric_type: "snmp_pppoe_highwater", derive: false, default: false},
  {id: 17, name: "Cisco: Per-slot CPU usage (1 min)", oid: "SNMPv2-SMI::enterprises.9.9.109.1.1.1.1.7", excludes: "", table: true, index_oid: "SNMPv2-SMI::enterprises.9.9.109.1.1.1.1.2", metric_type: "snmp_cpu", derive: false, default: false},
  {id: 18, name: "Cisco: IP Pool Used Addresses", oid: "SNMPv2-SMI::enterprises.9.9.326.1.2.2.1.2.0", excludes: "", table: false, index_oid: "", metric_type: "snmp_ip_pool_used", derive: false, default: false},
  {id: 19, name: "Cisco: IP Pool Free Addresses", oid: "SNMPv2-SMI::enterprises.9.9.326.1.2.2.1.1.0", excludes: "", table: false, index_oid: "", metric_type: "snmp_ip_pool_free", derive: false, default: false},
  {id: 20, name: "D-Link: CPU Usage", oid: "1.3.6.1.4.1.171.12.1.1.6.2.0", excludes: "", table: false, index_oid: "", metric_type: "snmp_cpu", derive: false, default: false}
])
